#!/usr/bin/env python3
"""Regenerate pinned tables; --data-dir reads checksum-verified files offline."""

import argparse
import hashlib
from pathlib import Path
import tempfile
from urllib.request import urlopen

VERSION = "18.0.0"
ROOT = Path(__file__).resolve().parents[2]
BASE = f"https://www.unicode.org/Public/{VERSION}"
SOURCES = {
    "confusables.txt": (
        f"{BASE}/security/confusables.txt",
        "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92",
    ),
    "UnicodeData.txt": (
        f"{BASE}/ucd/UnicodeData.txt",
        "0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950",
    ),
    "DerivedCoreProperties.txt": (
        f"{BASE}/ucd/DerivedCoreProperties.txt",
        "09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9",
    ),
    "license.txt": (
        "https://www.unicode.org/license.txt",
        "e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96",
    ),
}
LIMIT = 0x110000
# Assigned blanks not covered by categories or Default_Ignorable_Code_Point.
# See docs/unicode-data.md; ordinary combining marks remain displayable.
BLANKS = (0x2800, 0x13441, 0x13442, 0x16FE4)


def read_sources(directory, download):
    result = {}
    for name, (url, expected) in SOURCES.items():
        path = directory / name
        if download:
            with urlopen(url, timeout=60) as response:
                path.write_bytes(response.read())
        raw = path.read_bytes()
        actual = hashlib.sha256(raw).hexdigest()
        if actual != expected:
            raise ValueError(f"{name}: SHA256 {actual}, expected {expected}")
        result[name] = raw.decode("utf-8")
    return result


def records(text):
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if body:
            yield [field.strip() for field in body.split(";")]


def classify(data):
    confusable = bytearray(LIMIT)
    for fields in records(data["confusables.txt"]):
        source = fields[0].split()
        if len(source) != 1:
            raise ValueError(f"unexpected multi-code-point source: {fields[0]}")
        point = int(source[0], 16)
        if point >= 0x80:
            confusable[point] = 1

    # Missing code points are Cn (unassigned), hence non-displayable.
    hidden = bytearray(b"\1") * LIMIT
    marks = bytearray(LIMIT)
    first = None
    for fields in records(data["UnicodeData.txt"]):
        point, name, category = int(fields[0], 16), fields[1], fields[2]
        if name.endswith(", First>"):
            if first is not None:
                raise ValueError("nested UnicodeData range")
            first = (point, category)
            continue
        start = point
        if name.endswith(", Last>"):
            if first is None or first[1] != category:
                raise ValueError("invalid UnicodeData range")
            start, _ = first
            first = None
        elif first is not None:
            raise ValueError("unterminated UnicodeData range")
        hidden[start:point + 1] = bytes([category[0] not in "LMNPS"]) * (point + 1 - start)
        if category[0] == "M":
            marks[start:point + 1] = b"\1" * (point + 1 - start)
    if first is not None:
        raise ValueError("unterminated UnicodeData range")
    hidden[0x20] = 0
    for fields in records(data["DerivedCoreProperties.txt"]):
        if fields[1] == "Default_Ignorable_Code_Point":
            bounds = fields[0].split("..")
            start, end = int(bounds[0], 16), int(bounds[-1], 16)
            hidden[start:end + 1] = b"\1" * (end + 1 - start)
    for point in BLANKS:
        hidden[point] = 1
    return confusable, hidden, marks


def ranges(values):
    start = None
    for point, present in enumerate(values):
        if present and start is None:
            start = point
        elif not present and start is not None:
            yield start, point - 1
            start = None
    if start is not None:
        yield start, len(values) - 1


def generate(data):
    lines = [
        "// Code generated by gen_unicode.py; DO NOT EDIT.",
        f"// Unicode {VERSION}; sources and SHA256 checksums:",
    ]
    for url, digest in list(SOURCES.values())[:3]:
        lines.extend([f"// {url}", f"// SHA256: {digest}"])
    lines.extend([
        "// Unicode data copyright Unicode, Inc.; see ../../licenses/Unicode-3.0.txt.",
        "// Policy and regeneration: ../../docs/unicode-data.md.",
        "", "package prompt", "",
        "// isConfusable flags only non-ASCII mapping sources, never targets alone.",
        "// This is a context-free warning, not a font-aware spoofing detector.",
        "func isConfusable(r rune) bool {",
        "\treturn r >= 0x80 && inUnicodeRanges(r, confusableRanges[:])", "}", "",
        "// isNonDisplayable uses pinned categories and default-ignorable properties,",
        "// plus explicit blank exceptions. The renderer handles tabs/newlines itself.",
        "func isNonDisplayable(r rune) bool {",
        "\tif r < 0x80 {",
        "\t\treturn r < 0x20 || r == 0x7F",
        "\t}",
        "\treturn r > 0x10FFFF || inUnicodeRanges(r, nonDisplayableRanges[:])",
        "}", "",
        "// isCombiningMark recognizes pinned Mn/Mc/Me categories for cluster styling.",
        "func isCombiningMark(r rune) bool {",
        "\tif r < 0x0300 {",
        "\t\treturn false",
        "\t}",
        "\treturn inUnicodeRanges(r, combiningMarkRanges[:])", "}", "",
        "type unicodeRange struct{ lo, hi rune }", "",
        "func inUnicodeRanges(r rune, ranges []unicodeRange) bool {",
        "\tlo, hi := 0, len(ranges)",
        "\tfor lo < hi {",
        "\t\tmid := lo + (hi-lo)/2",
        "\t\tspan := ranges[mid]",
        "\t\tif r < span.lo {",
        "\t\t\thi = mid",
        "\t\t} else if r > span.hi {",
        "\t\t\tlo = mid + 1",
        "\t\t} else {",
        "\t\t\treturn true", "\t\t}", "\t}", "\treturn false", "}", "",
    ])
    for name, values in zip(("confusableRanges", "nonDisplayableRanges", "combiningMarkRanges"), classify(data)):
        spans = list(ranges(values))
        lines.append(f"// {sum(values)} code points in {len(spans)} sorted, disjoint ranges.")
        lines.append(f"var {name} = [...]unicodeRange{{")
        for i in range(0, len(spans), 3):
            lines.append("\t" + " ".join(f"{{0x{lo:04X}, 0x{hi:04X}}}," for lo, hi in spans[i:i + 3]))
        lines.extend(["}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, help="read all four source files locally; no network")
    parser.add_argument("--check", action="store_true", help="compare without modifying generated files")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="jj-unicode-") as temporary:
        data = read_sources(args.data_dir or Path(temporary), download=args.data_dir is None)
    outputs = {
        ROOT / "internal/prompt/unicode_tables.go": generate(data),
        ROOT / "licenses/Unicode-3.0.txt": data["license.txt"],
    }
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes() != text.encode("utf-8"):
                raise SystemExit(f"out of date: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))


if __name__ == "__main__":
    main()
